return {
	ui = {
		hover = {
			SoundId = "rbxassetid://109776571563606",
			Volume = 1.4,
			PlaybackRegion = NumberRange.new(0.05, 1),
		},

		mouseDown = {
			SoundId = "rbxassetid://18202483174",
			Volume = 0.5,
			PlaybackRegion = NumberRange.new(0, 0.07),
		},

		mouseUp = {
			SoundId = "rbxassetid://18202483174",
			Volume = 0.8,
			PlaybackRegion = NumberRange.new(0.07, 999),
		},
	},
}
