return {
	ui = {
		hover = {
			SoundId = "rbxassetid://109776571563606",
			Volume = 1.4,
			PlaybackRegion = NumberRange.new(0.05, 1),
		},

		mouseDown = {
			SoundId = "rbxassetid://18202483174",
			Volume = 0.5,
			PlaybackRegion = NumberRange.new(0, 0.07),
		},

		mouseUp = {
			SoundId = "rbxassetid://18202483174",
			Volume = 0.8,
			PlaybackRegion = NumberRange.new(0.07, 999),
		},

		click = {
			SoundId = "rbxassetid://71294801358152",
			Volume = 1,
		},

		notification = {
			SoundId = "rbxassetid://4612375802",
			Volume = 0.5,
		},
	},

	misc = {
		--[[
		roll = {
			SoundId = "rbxassetid://82676714368656",
			Volume = 2.5,
		},

		rollEnd = {
			SoundId = "rbxassetid://110964600384165",
			Volume = 1,
		},

		crateCharge = {
			SoundId = "rbxassetid://9117297289",
			Volume = 1,
			PlaybackRegion = NumberRange.new(0.4, 999),
		},

		crateUnlock = {
			SoundId = "rbxassetid://9125963470",
			Volume = 1.5,
			PlaybackRegion = NumberRange.new(0.2, 999),
		},

		woosh = {
			SoundId = "rbxassetid://9114374439",
			Volume = 2,
			PlaybackRegion = NumberRange.new(0.14, 999),
		},
		]]
	},
}
